---
name: check src branch name

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [rel-*]
  workflow_dispatch:

jobs:
  check-src-branch-name:
    uses: appaegis/gitaction-lib/.github/workflows/check-pr-source-branch-name.yaml@main
    with:
      repository: ${{ github.repository }}
      target_branch: ${{ github.event.pull_request.base.ref }}
      pr_title: ${{ github.event.pull_request.title }}
    secrets:
      username: ${{ secrets.GIT_USER }}
      token: ${{ secrets.ORG_TOKEN }}
