---
name: Review PR message body

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [dev, rel-3*]
  workflow_dispatch:

jobs:
  review-pr-message-body:
    uses: appaegis/gitaction-lib/.github/workflows/review-pr-message-body.yml@main
    with:
      event_path: ${GITHUB_EVENT_PATH}
